default_agent: agentcore_starter_strands
agents:
  agentcore_starter_strands:
    name: agentcore_starter_strands
    entrypoint: D:/Code/github/Bedrock_agent/agentcore_starter_strands.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: D:\Code\github\Bedrock_agent
    aws:
      execution_role: arn:aws:iam::566801649110:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-1-9c0804ec0c
      execution_role_auto_create: false
      account: '566801649110'
      region: ap-southeast-1
      ecr_repository: 566801649110.dkr.ecr.ap-southeast-1.amazonaws.com/bedrock-agentcore-agentcore_starter_strands
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_starter_strands-nx5I2v2Mvt
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-1:566801649110:runtime/agentcore_starter_strands-nx5I2v2Mvt
      agent_session_id: 8914ab8e-9795-4ebf-9c4a-3789e22ffba4
    codebuild:
      project_name: bedrock-agentcore-agentcore_starter_strands-builder
      execution_role: arn:aws:iam::566801649110:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-1-9c0804ec0c
      source_bucket: bedrock-agentcore-codebuild-sources-566801649110-ap-southeast-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_starter_strands_mem-AWJdJjCNI8
      memory_arn: null
      memory_name: agentcore_starter_strands_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
