default_agent: strands_claude_getting_started_20251126_162016
agents:
  strands_claude_getting_started_20251126_162016:
    name: strands_claude_getting_started_20251126_162016
    entrypoint: D:/Code/github/Bedrock_agent/bedrock_agentcore_agent_E2E/deploy/strands_claude.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::566801649110:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-1-4a92b983c8
      execution_role_auto_create: false
      account: '566801649110'
      region: ap-southeast-1
      ecr_repository: 566801649110.dkr.ecr.ap-southeast-1.amazonaws.com/bedrock-agentcore-strands_claude_getting_started_20251126_162016
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_claude_getting_started_20251126_162016-6C3Zra4PL2
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-1:566801649110:runtime/strands_claude_getting_started_20251126_162016-6C3Zra4PL2
      agent_session_id: ac0edbf5-d006-4ae6-8f74-94132c113759
    codebuild:
      project_name: bedrock-agentcore-strands_claude_getting_started_20251126_162016-builder
      execution_role: arn:aws:iam::566801649110:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-1-4a92b983c8
      source_bucket: bedrock-agentcore-codebuild-sources-566801649110-ap-southeast-1
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
